animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

animals[1]
animals[2]
animals[0]
animals[3]
animals[4]
animals[2]
animals[5]
animals[4]

print "The animal at one is a %s" % animals[1]
print "The third animal is at 2 and is a %s" % animals[2]
print "The first animal is at 0 and is a %s" % animals[0]
print "The animal at 3 is a %s" % animals[3]
print "The fifth animal is at 4 and is a %s" % animals[4]
print "The animal at 2 is a %s" % animals[2]
print "The sixth animal is at 5 and is a %s" % animals[5]
print "The animal at 4 is a %s" % animals[4]
